<?php

namespace TyHand\BackgroundProcessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobEntityRepository extends EntityRepository
{
    /**
     * Get events that have not yet been processed or are being processed
     * 
     * @param  int   $limit The maximum number of events to grab
     * 
     * @return array        The queued jobs
     */
    public function getQueuedJobs($limit = null) {
        //Create a querybuilder
        $qb = $this->createQueryBuilder('job');

        //Join on the job status table to get jobs with a status of queued
        $qb
            ->select('job')
            ->join('job.currentStatus', 'jobStatus')
            ->join('jobStatus.status', 'status')
            ->where('status.shortName = :queueStatus')
            ->setParameter('queueStatus', 'In Queue')
        ;

        if (null !== $limit) {
            $qb->setMaxResults($limit);
        }

        //Return the jobs
        return $qb->getQuery()->getResult();
    }
}
