<?php

namespace TyHand\BackgroundProcessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobStatusEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobStatusEntityRepository extends EntityRepository
{
}
