<?php

namespace TyHand\BackgroundProcessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatusEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusEntityRepository extends EntityRepository
{
    /**
     * Get all of the status entities from the database
     * 
     * @return array All of the status entities
     */
    public function getAll() {
        return $this->createQueryBuilder('status')->select('status')->getQuery()->getResult();
    }
}
